const KEY="RECO_MT_V4";
const ADMIN_PIN="2609";
const today=()=>new Date().toISOString().slice(0,10);
const demo={
 session:{name:"Sebastián Díaz",role:"admin"},
 reconectadores:[
 {id:1,codigo:"RC-01",marca:"NOJA Power",modelo:"OSM",serie:"NJP-001",alimentador:"52C26 Boro",ubicacion:"Patillos",lat:"-20.2755",lon:"-70.1140",estado:"Operativo",instalacion:"2024-03-12",ultima:"2026-06-14",proxima:"2027-06-14",control:"RC-10",firmware:"SGA CMS",observaciones:"Equipo operativo y disponible."},
 {id:2,codigo:"RC-10",marca:"NOJA Power",modelo:"OSM",serie:"NJP-010",alimentador:"52C10",ubicacion:"Iquique urbano",lat:"-20.2307",lon:"-70.1357",estado:"Con observaciones",instalacion:"2024-04-10",ultima:"2026-04-11",proxima:"2026-10-11",control:"RC-10",firmware:"SGA CMS",observaciones:"Revisar parámetros de restauración y batería."},
 {id:3,codigo:"RC-04",marca:"Arteche",modelo:"Recloser",serie:"ART-004",alimentador:"52C04 Victoria",ubicacion:"Sector Norte",lat:"-20.2135",lon:"-70.1410",estado:"Operativo",instalacion:"2023-11-20",ultima:"2026-03-20",proxima:"2027-03-20",control:"Arteche",firmware:"-",observaciones:"Sin novedades."},
 {id:4,codigo:"RC-06",marca:"NOJA Power",modelo:"OSM",serie:"NJP-006",alimentador:"52C06",ubicacion:"Zona Industrial",lat:"-20.2440",lon:"-70.1270",estado:"Fuera de servicio",instalacion:"2023-08-18",ultima:"2025-11-03",proxima:"2026-11-03",control:"RC-01",firmware:"SGA CMS",observaciones:"Pendiente intervención y diagnóstico."},
 {id:5,codigo:"RC-12",marca:"NOJA Power",modelo:"OSM",serie:"NJP-012",alimentador:"52C12",ubicacion:"Alto Hospicio",lat:"-20.2680",lon:"-70.1030",estado:"Operativo",instalacion:"2025-01-22",ultima:"2026-02-10",proxima:"2027-02-10",control:"RC-10",firmware:"SGA CMS",observaciones:"Operación normal."}
 ],
 inspecciones:[
 {id:101,equipo:"RC-01",fecha:"2026-09-20",inspector:"Sebastián Díaz",resultado:"Conforme",operaciones:125,tension:13.2,comunicaciones:"Normal",observaciones:"Sin hallazgos. Limpieza y revisión visual conforme.",checklist:{visual:true,gabinete:true,bateria:true,apertura:true,cierre:true,protecciones:true,tierra:true,limpieza:true}},
 {id:102,equipo:"RC-10",fecha:"2026-09-18",inspector:"Sebastián Díaz",resultado:"Con observaciones",operaciones:87,tension:11.8,comunicaciones:"Intermitente",observaciones:"Se recomienda revisar batería y comunicación.",checklist:{visual:true,gabinete:true,bateria:false,apertura:true,cierre:true,protecciones:true,tierra:true,limpieza:true}},
 {id:103,equipo:"RC-04",fecha:"2026-09-10",inspector:"Sebastián Díaz",resultado:"Conforme",operaciones:62,tension:13.4,comunicaciones:"Normal",observaciones:"Equipo sin novedades.",checklist:{visual:true,gabinete:true,bateria:true,apertura:true,cierre:true,protecciones:true,tierra:true,limpieza:true}}
 ]};
let state=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(demo);
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function isAdmin(){return state.session.role==="admin"}
function toast(m){let t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function openModal(id){document.getElementById(id).showModal()}
function closeModal(id){document.getElementById(id).close()}
function fmtDate(s){if(!s)return"-";let a=s.split("-");return `${a[2]}-${a[1]}-${a[0]}`}
function badge(t){let x=(t||"").toLowerCase(),c="info";if(x.includes("operativo")||x.includes("conforme")||x.includes("normal"))c="ok";if(x.includes("observ")||x.includes("intermitente"))c="warn";if(x.includes("fuera")||x.includes("intervención")||x.includes("sin comunicación"))c="danger";return `<span class="badge ${c}">${t}</span>`}
function daysUntil(s){if(!s)return 99999;let a=new Date();a.setHours(0,0,0,0);let b=new Date(s+"T00:00:00");return Math.ceil((b-a)/86400000)}
function renderAccess(){modePill.textContent=isAdmin()?`${state.session.name} · Administrador`:`${state.session.name} · Solo consulta`;document.querySelectorAll(".adminOnly").forEach(e=>e.style.display=isAdmin()?"":"none")}
function renderDashboard(){
 let total=state.reconectadores.length,op=state.reconectadores.filter(r=>r.estado==="Operativo").length,obs=state.reconectadores.filter(r=>r.estado==="Con observaciones").length,off=state.reconectadores.filter(r=>r.estado==="Fuera de servicio").length,ins=state.inspecciones.length;
 let data=[["⚡","Reconectadores",total],["✅","Operativos",op],["⚠️","Con observaciones",obs],["⛔","Fuera de servicio",off],["📝","Inspecciones",ins]];
 kpis.innerHTML=data.map(x=>`<div class="card"><div class="icon">${x[0]}</div><div class="label">${x[1]}</div><div class="value">${x[2]}</div></div>`).join("");
 let pct=v=>total?Math.round(v/total*100):0;
 fleetHealth.innerHTML=`<div class="healthRow"><strong>Operativos</strong><div class="healthTrack"><div class="healthFill fillGreen" style="width:${pct(op)}%"></div></div><strong>${pct(op)}%</strong></div><div class="healthRow"><strong>Observación</strong><div class="healthTrack"><div class="healthFill fillAmber" style="width:${pct(obs)}%"></div></div><strong>${pct(obs)}%</strong></div><div class="healthRow"><strong>Fuera servicio</strong><div class="healthTrack"><div class="healthFill fillRed" style="width:${pct(off)}%"></div></div><strong>${pct(off)}%</strong></div>`;
 recentActivity.innerHTML=state.inspecciones.slice().sort((a,b)=>b.fecha.localeCompare(a.fecha)).slice(0,6).map(i=>`<div class="listRow"><div><strong>${i.equipo} · ${i.inspector}</strong><span class="tiny">${fmtDate(i.fecha)} · ${i.observaciones}</span></div>${badge(i.resultado)}</div>`).join("");
 attentionStrip.innerHTML=state.reconectadores.filter(r=>r.estado!=="Operativo"||daysUntil(r.proxima)<=30).map(r=>`<div class="attentionCard ${r.estado==="Fuera de servicio"?"dangerBox":""}"><strong>${r.codigo} · ${r.ubicacion}</strong><div class="tiny">${r.alimentador}</div><div style="margin-top:8px">${badge(r.estado)}</div></div>`).join("")||`<span class="muted">Sin equipos que requieran atención inmediata.</span>`;
}
function renderFilters(){let brands=[...new Set(state.reconectadores.map(r=>r.marca))].sort();filterBrand.innerHTML=`<option value="">Todas las marcas</option>`+brands.map(b=>`<option>${b}</option>`).join("")}
function renderRecos(){let q=(searchReco.value||"").toLowerCase(),f=filterStatus.value,b=filterBrand.value;let arr=state.reconectadores.filter(r=>(!f||r.estado===f)&&(!b||r.marca===b)&&Object.values(r).join(" ").toLowerCase().includes(q));recoGrid.innerHTML=arr.map(r=>{let cls=r.estado==="Con observaciones"?"warnCard":r.estado==="Fuera de servicio"?"dangerCard":"";let last=state.inspecciones.filter(i=>i.equipo===r.codigo).sort((a,b)=>b.fecha.localeCompare(a.fecha))[0];return `<div class="recoCard ${cls}" onclick="showReco(${r.id})"><span class="eyebrow">${r.alimentador}</span><div class="recoCode">${r.codigo}</div>${badge(r.estado)}<div class="metaGrid"><div class="metaBox"><span>Marca / modelo</span><strong>${r.marca} ${r.modelo||""}</strong></div><div class="metaBox"><span>Ubicación</span><strong>${r.ubicacion}</strong></div><div class="metaBox"><span>Última inspección</span><strong>${last?fmtDate(last.fecha):"Sin registro"}</strong></div><div class="metaBox"><span>Próxima mantención</span><strong>${fmtDate(r.proxima)}</strong></div></div><button class="btn primary">Abrir ficha técnica</button></div>`}).join("")||`<p class="muted">No hay equipos que coincidan con la búsqueda.</p>`}
function renderMap(){let lats=state.reconectadores.map(r=>Number(r.lat)).filter(Number.isFinite),lons=state.reconectadores.map(r=>Number(r.lon)).filter(Number.isFinite);let minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons);mapSurface.innerHTML=`<div class="map-label">Vista esquemática · posiciones relativas</div>`+state.reconectadores.map(r=>{let lat=Number(r.lat),lon=Number(r.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return"";let x=((lon-minLon)/(maxLon-minLon||1))*75+12.5;let y=(1-(lat-minLat)/(maxLat-minLat||1))*72+14;return `<div class="mapMarker" style="left:${x}%;top:${y}%" onclick="showReco(${r.id})"><div class="markerDot"></div><span>${r.codigo}</span></div>`}).join("");mapList.innerHTML=state.reconectadores.map(r=>`<div class="listRow"><div><strong>${r.codigo} · ${r.ubicacion}</strong><span class="tiny">${r.lat}, ${r.lon} · ${r.alimentador}</span></div><div><button class="btn ghost" onclick="showReco(${r.id})">Ficha</button> <button class="btn ghost" onclick="window.open('https://www.google.com/maps?q=${r.lat},${r.lon}','_blank')">Mapa</button></div></div>`).join("")}
function showReco(id){let r=state.reconectadores.find(x=>x.id===id);if(!r)return;let ins=state.inspecciones.filter(i=>i.equipo===r.codigo).sort((a,b)=>b.fecha.localeCompare(a.fecha));let last=ins[0];detailTitle.textContent=`${r.codigo} · ${r.ubicacion}`;detailContent.innerHTML=`<div class="detailHero"><div class="detailMain"><span class="eyebrow">${r.alimentador}</span><h2>${r.codigo}</h2>${badge(r.estado)}<p>${r.observaciones||"Sin observaciones técnicas."}</p>${isAdmin()?`<div style="margin-top:14px;display:flex;gap:8px;flex-wrap:wrap"><button class="btn secondary" onclick="editReco(${r.id})">Editar equipo</button><button class="btn secondary" onclick="closeModal('detailModal');openInspection('${r.codigo}')">+ Nueva inspección</button></div>`:""}</div><div class="detailAside"><h3>Estado actual</h3><div class="inspectionCard">${last?`<div class="inspectionTop"><strong>Última inspección</strong>${badge(last.resultado)}</div><p>${fmtDate(last.fecha)} · ${last.inspector}</p><p class="muted">${last.observaciones}</p>`:"<p class='muted'>Sin inspecciones registradas.</p>"}</div><button class="btn primary" onclick="window.open('https://www.google.com/maps?q=${r.lat},${r.lon}','_blank')">📍 Ver ubicación</button></div></div><div class="detailStats"><div class="stat"><span>Marca / modelo</span><strong>${r.marca} ${r.modelo||""}</strong></div><div class="stat"><span>N° serie</span><strong>${r.serie||"-"}</strong></div><div class="stat"><span>Control</span><strong>${r.control||"-"}</strong></div><div class="stat"><span>Firmware</span><strong>${r.firmware||"-"}</strong></div><div class="stat"><span>Alimentador</span><strong>${r.alimentador||"-"}</strong></div><div class="stat"><span>Instalación</span><strong>${fmtDate(r.instalacion)}</strong></div><div class="stat"><span>Últ. mantención</span><strong>${fmtDate(r.ultima)}</strong></div><div class="stat"><span>Próx. mantención</span><strong>${fmtDate(r.proxima)}</strong></div></div><h3>Historial de inspecciones</h3><div class="history">${ins.map(i=>`<div class="historyItem"><h4>${fmtDate(i.fecha)} · ${i.inspector}</h4><p>${badge(i.resultado)} · Batería ${i.tension||"-"} V · Comunicación ${i.comunicaciones}</p><p>${i.observaciones||"Sin observaciones."}</p></div>`).join("")||`<p class="muted">Sin inspecciones registradas.</p>`}</div>`;openModal("detailModal")}
function newReco(){if(!isAdmin())return;recoForm.reset();recoForm.id.value="";recoFormTitle.textContent="Nuevo reconectador";openModal("recoModal")}
function editReco(id){if(!isAdmin())return;let r=state.reconectadores.find(x=>x.id===id);if(!r)return;for(let k in r){if(recoForm.elements[k])recoForm.elements[k].value=r[k]??""}recoFormTitle.textContent=`Editar ${r.codigo}`;closeModal("detailModal");openModal("recoModal")}
recoForm.addEventListener("submit",e=>{e.preventDefault();if(!isAdmin())return;let o=Object.fromEntries(new FormData(e.target)),id=Number(o.id);delete o.id;if(id){let idx=state.reconectadores.findIndex(x=>x.id===id);state.reconectadores[idx]={...state.reconectadores[idx],...o}}else state.reconectadores.push({id:Date.now(),...o});closeModal("recoModal");save();toast("Reconectador actualizado")});
function openInspection(code){if(!isAdmin())return;inspectionForm.reset();inspectionForm.equipo.value=code;inspectionForm.fecha.value=today();inspectionForm.inspector.value=state.session.name;document.querySelectorAll(".checkGrid input").forEach(x=>x.checked=true);inspectionTitle.textContent=code;openModal("inspectionModal")}
inspectionForm.addEventListener("submit",e=>{e.preventDefault();if(!isAdmin())return;let f=new FormData(e.target),check={};document.querySelectorAll(".checkGrid input").forEach(x=>check[x.name]=x.checked);state.inspecciones.push({id:Date.now(),equipo:f.get("equipo"),fecha:f.get("fecha"),inspector:f.get("inspector"),resultado:f.get("resultado"),operaciones:Number(f.get("operaciones")||0),tension:Number(f.get("tension")||0),comunicaciones:f.get("comunicaciones"),observaciones:f.get("observaciones"),checklist:check});closeModal("inspectionModal");save();toast("Inspección registrada")});
function openAccess(){accessName.value=state.session.name||"";accessRole.value=state.session.role;accessPin.value="";pinLabel.style.display=accessRole.value==="admin"?"":"none";openModal("accessModal")}
accessRole.addEventListener("change",()=>pinLabel.style.display=accessRole.value==="admin"?"":"none");
function login(){let n=accessName.value.trim();if(!n)return toast("Ingresa un nombre");if(accessRole.value==="admin"&&accessPin.value!==ADMIN_PIN)return toast("PIN incorrecto");state.session={name:n,role:accessRole.value};closeModal("accessModal");save();toast(isAdmin()?"Modo administrador":"Modo consulta")}
function goView(id){document.querySelector(`[data-view="${id}"]`).click()}
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{if(b.dataset.view==="administrar"&&!isAdmin())return;document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(x=>x.classList.remove("active-view"));document.getElementById(b.dataset.view).classList.add("active-view");if(b.dataset.view==="mapa")renderMap()}));
searchReco.addEventListener("input",renderRecos);filterStatus.addEventListener("change",renderRecos);filterBrand.addEventListener("change",renderRecos);
function downloadBackup(){let b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`reconectadores_mt_${today()}.json`;a.click();URL.revokeObjectURL(u)}
function renderAll(){renderAccess();renderDashboard();renderFilters();renderRecos();renderMap()}
renderAll();