// Porcentajes visibles sobre el gráfico Estado de la flota.
(function(){
  if(typeof Chart==='undefined')return;
  const plugin={id:'statusPercentageLabels',afterDatasetsDraw(chart){
    if(chart.canvas?.id!=='gStatusChart')return;
    const ds=chart.data?.datasets?.[0],meta=chart.getDatasetMeta(0);if(!ds||!meta)return;
    const vals=(ds.data||[]).map(v=>Number(v)||0),total=vals.reduce((a,b)=>a+b,0);if(!total)return;
    const ctx=chart.ctx;ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='700 13px Inter, Segoe UI, Arial, sans-serif';ctx.fillStyle='#fff';ctx.shadowColor='rgba(0,0,0,.35)';ctx.shadowBlur=3;
    meta.data.forEach((arc,i)=>{const v=vals[i];if(!v)return;const angle=Math.abs((arc.endAngle||0)-(arc.startAngle||0));if(angle<0.16)return;const p=arc.tooltipPosition(),pc=v*100/total;ctx.fillText((pc<10?pc.toFixed(1):Math.round(pc))+'%',p.x,p.y);});ctx.restore();
  }};
  try{Chart.register(plugin);}catch(_){ }
})();

// Informe PDF espejo de la pestaña Gestión.
(function(){
  const pct=(n,d)=>d?Math.round(n*100/d):0;
  const allRows=()=>window.state?.reconectadores||[];
  const inspections=()=>window.state?.inspecciones||[];
  const fmt=v=>{if(!v)return '-';const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('es-CL');};
  function stamp(){const d=new Date();return {date:d.toLocaleDateString('es-CL'),time:d.toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'}),file:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}_${String(d.getHours()).padStart(2,'0')}-${String(d.getMinutes()).padStart(2,'0')}`};}
  function rows(){const q=document.getElementById('gQuadrant')?.value||'',s=document.getElementById('gStatus')?.value||'',g=document.getElementById('gGestor')?.value||'';return allRows().filter(r=>(!q||String(r.cuadrante||'')===q)&&(!s||r.estado===s)&&(!g||String(r.gestor_cuadrante||'')===g));}
  function filterLabel(){const a=[],q=document.getElementById('gQuadrant')?.value||'',s=document.getElementById('gStatus')?.value||'',g=document.getElementById('gGestor')?.value||'';if(q)a.push('Cuadrante '+q);if(s)a.push(s);if(g)a.push(g);return a.join(' · ')||'Vista general de la flota';}
  function stats(rs){const total=rs.length,oper=rs.filter(r=>r.estado==='Operativo').length,obs=rs.filter(r=>r.estado==='Con observaciones').length,fuera=rs.filter(r=>r.estado==='Fuera de servicio').length,geo=rs.filter(r=>Number.isFinite(Number(r.lat))&&Number.isFinite(Number(r.lon))).length,verif=rs.filter(r=>r.fecha_verificacion).length;const now=new Date(),codes=new Set(rs.map(r=>r.codigo)),monthIns=inspections().filter(i=>{if(!i.fecha||!codes.has(i.equipo))return false;const d=new Date(i.fecha+'T00:00:00');return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth();}).length;return {total,oper,obs,fuera,geo,verif,monthIns};}
  function qSummary(rs){const qs=[...new Set(rs.map(r=>String(r.cuadrante||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));return qs.map(q=>{const a=rs.filter(r=>String(r.cuadrante||'')===q),op=a.filter(r=>r.estado==='Operativo').length,gs=[...new Set(a.map(r=>String(r.gestor_cuadrante||'').trim()).filter(Boolean))];return [q,gs.join(' / ')||'Sin gestor',a.length,op,a.filter(r=>r.estado!=='Operativo').length,pct(op,a.length)+'%'];});}
  function gestores(rs){const map=new Map();rs.forEach(r=>{const q=String(r.cuadrante||'').trim();if(!q)return;const key=q;if(!map.has(key))map.set(key,{q,gs:new Set(),n:0});const o=map.get(key);if(String(r.gestor_cuadrante||'').trim())o.gs.add(String(r.gestor_cuadrante).trim());o.n++;});return [...map.values()].sort((a,b)=>a.q.localeCompare(b.q,undefined,{numeric:true}));}
  function pending(rs){return rs.filter(r=>r.estado!=='Operativo'||!r.fecha_verificacion||!(Number.isFinite(Number(r.lat))&&Number.isFinite(Number(r.lon)))).sort((a,b)=>{const rank=x=>x.estado==='Fuera de servicio'?0:x.estado==='Con observaciones'?1:!x.fecha_verificacion?2:3;return rank(a)-rank(b)||String(a.codigo).localeCompare(String(b.codigo),'es',{numeric:true});});}
  function why(r){if(r.estado!=='Operativo')return r.estado;if(!r.fecha_verificacion)return 'Sin fecha de verificación';return 'Sin coordenadas';}
  function header(doc,title,sub){const w=doc.internal.pageSize.getWidth();doc.setFillColor(15,39,69);doc.rect(0,0,w,27,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text(title,14,11);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(sub,14,19);doc.setTextColor(35,48,66);}
  function footer(doc){const n=doc.getNumberOfPages();for(let i=1;i<=n;i++){doc.setPage(i);const w=doc.internal.pageSize.getWidth(),h=doc.internal.pageSize.getHeight();doc.setDrawColor(225);doc.line(14,h-11,w-14,h-11);doc.setFontSize(7);doc.setTextColor(115);doc.text('Reconectadores MT · Delegación Iquique',14,h-6);doc.text(`Página ${i} de ${n}`,w-14,h-6,{align:'right'});}}
  function chartImg(id){const c=document.getElementById(id);if(!c||!c.width||!c.height)return null;try{return c.toDataURL('image/png',1)}catch(_){return null}}
  function chartBox(doc,id,title,x,y,w,h){const img=chartImg(id);if(!img)return false;doc.setFillColor(255);doc.setDrawColor(225,230,236);doc.roundedRect(x,y,w,h,3,3,'FD');doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(35,50,70);doc.text(title,x+5,y+7);doc.addImage(img,'PNG',x+4,y+11,w-8,h-15,'','FAST');return true;}
  function kpi(doc,label,value,sub,x,y,w=42,h=20){doc.setFillColor(255);doc.setDrawColor(225,230,236);doc.roundedRect(x,y,w,h,3,3,'FD');doc.setFont('helvetica','normal');doc.setFontSize(6.5);doc.setTextColor(115,125,140);doc.text(label.toUpperCase(),x+4,y+5);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.setTextColor(24,37,57);doc.text(String(value),x+4,y+12.5);doc.setFont('helvetica','normal');doc.setFontSize(6.2);doc.setTextColor(115,125,140);doc.text(String(sub||''),x+4,y+17);}
  async function build(){if(!window.jspdf?.jsPDF)throw new Error('No se pudo cargar el generador PDF.');const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});if(typeof doc.autoTable!=='function')throw new Error('No se pudo cargar el módulo de tablas PDF.');const rs=rows(),s=stats(rs),t=stamp(),filter=filterLabel(),qs=qSummary(rs),gs=gestores(rs),pend=pending(rs);
    header(doc,'Gestión de activos MT',`Control de Gestión · ${t.date} ${t.time} · ${filter}`);
    doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(35,50,70);doc.text('Indicadores de gestión',14,38);
    const cards=[['Equipos en vista',s.total,filter==='Vista general de la flota'?'Base completa':'Resultado filtrado'],['Disponibilidad',pct(s.oper,s.total)+'%',s.oper+' operativos'],['Requieren atención',s.obs+s.fuera,`${s.obs} observados · ${s.fuera} fuera`],['Georreferenciación',pct(s.geo,s.total)+'%',s.geo+' con coordenadas'],['Fecha verificación',pct(s.verif,s.total)+'%',s.verif+' con fecha registrada'],['Inspecciones del mes',s.monthIns,'Sobre equipos visibles'],['Observaciones',s.obs,'Estado actual'],['Fuera de servicio',s.fuera,'Atención prioritaria']];
    cards.forEach((c,i)=>{const col=i%4,row=Math.floor(i/4);kpi(doc,c[0],c[1],c[2],14+col*46,44+row*24,42,20);});
    chartBox(doc,'gStatusChart','Estado de la flota',14,100,86,72);chartBox(doc,'gQuadrantChart','Equipos por cuadrante',110,100,86,72);
    doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Resumen por cuadrante',14,184);
    doc.autoTable({startY:188,head:[['Cuadrante','Gestor','Total','Operativos','Atención','Disp.']],body:qs,theme:'striped',styles:{fontSize:7,cellPadding:2,textColor:[50,62,78]},headStyles:{fillColor:[23,76,128],textColor:255},columnStyles:{0:{cellWidth:24},1:{cellWidth:50},2:{halign:'center'},3:{halign:'center'},4:{halign:'center'},5:{halign:'center'}},margin:{left:14,right:14,bottom:16}});
    doc.addPage();header(doc,'Análisis visual de Gestión','Actividad, referencias y calidad de información');
    chartBox(doc,'gInspectionChart','Actividad de inspecciones · últimos 6 meses',14,38,182,70);
    chartBox(doc,'gBrandChart','Equipos por referencia',14,119,86,72);chartBox(doc,'gDataChart','Calidad de información',110,119,86,72);
    doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Gestores por cuadrante',14,204);
    const x0=14,y0=210,w=56,h=22;gs.forEach((g,i)=>{const col=i%3,row=Math.floor(i/3),x=x0+col*61,y=y0+row*27;doc.setFillColor(248,250,252);doc.setDrawColor(230,234,239);doc.roundedRect(x,y,w,h,2,2,'FD');doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(35,50,70);doc.text('Cuadrante '+g.q,x+4,y+6);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.setTextColor(82,97,116);const name=[...g.gs].join(' / ')||'Sin gestor asignado';doc.text(doc.splitTextToSize(name,w-8),x+4,y+12);doc.setFontSize(6.5);doc.text(`${g.n} equipos`,x+4,y+h-3);});
    doc.addPage();header(doc,'Pendientes de Gestión',`${pend.length} detectados en la vista actual · priorización operacional`);
    if(pend.length){doc.autoTable({startY:36,head:[['Equipo','Alimentador','Estado / motivo','Cuadrante','Gestor','Verificación','Observaciones']],body:pend.map(r=>[r.codigo||'-',r.alimentador||'-',why(r),r.cuadrante||'-',r.gestor_cuadrante||'-',fmt(r.fecha_verificacion),r.observaciones||'-']),theme:'grid',styles:{fontSize:7,cellPadding:2,valign:'top',overflow:'linebreak',textColor:[48,60,76]},headStyles:{fillColor:[15,39,69],textColor:255},columnStyles:{0:{cellWidth:23},1:{cellWidth:28},2:{cellWidth:30},3:{cellWidth:17},4:{cellWidth:30},5:{cellWidth:23},6:{cellWidth:35}},margin:{left:8,right:8,bottom:18}});}else{doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(85,98,115);doc.text('No hay pendientes para este filtro.',14,42);}
    footer(doc);return {doc,filename:`Gestion_Reconectadores_MT_${t.file}.pdf`};
  }
  async function generate(share){const btn=document.getElementById('enviarGestionCorreoPDF');if(btn){btn.disabled=true;btn.textContent='Generando PDF...';}try{const {doc,filename}=await build(),blob=doc.output('blob'),file=new File([blob],filename,{type:'application/pdf'});if(share&&navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Gestión Reconectadores MT',text:'Adjunto respaldo visual de Gestión de Reconectadores MT.',files:[file]});}else{doc.save(filename);if(typeof toast==='function')toast('PDF generado correctamente.');}}catch(e){console.error(e);if(typeof toast==='function')toast(e.message||'No fue posible generar el PDF');else alert(e.message||'No fue posible generar el PDF');}finally{if(btn){btn.disabled=false;btn.textContent='📄 Generar / compartir PDF';}}}
  function install(){const old=document.getElementById('enviarGestionCorreo')||document.getElementById('enviarGestionCorreoPDF');if(!old)return;if(old.id!=='enviarGestionCorreoPDF'){const b=old.cloneNode(true);b.id='enviarGestionCorreoPDF';old.replaceWith(b);}const btn=document.getElementById('enviarGestionCorreoPDF');btn.textContent='📄 Generar / compartir PDF';btn.onclick=()=>generate(true);const sm=document.querySelector('#gestionRespaldoBar small');if(sm)sm.textContent='Genera un PDF con la misma estructura visual e información de la pestaña Gestión.';}
  document.addEventListener('click',e=>{if(e.target.closest('[data-view="gestion"]'))setTimeout(install,180);});const host=document.getElementById('gestionContent');if(host)new MutationObserver(()=>setTimeout(install,0)).observe(host,{childList:true,subtree:true});setTimeout(install,1200);window.generarInformeGestionPDF=()=>generate(false);
})();